### ISSUE TITLE
gold_ore.png & gold_ore_e.png Missing All of Their Animation Frames

### ISSUE THREAD

**Issue by NyaXayN** [giteczek/Aminated-Ore-Frame#1]
In all of the released version of the texture pack the golden_ore.png and gold_ore_e.png only have a single frame of animation.
I have taken the liberty to add the frame onto the animating present in Animated-Ore's gold_ore.png. I'm too lazy to do the same thing for gold_ore_e.png since I do not use its property. However I am sure this will be an easy fix.

![gold_ore](https://github.com/raspberrygitq/Aminated-Ore-Frame/assets/117741756/3b01a130-8db5-4285-b11a-3585510b87b4)

**Comment by raspberrygitq** [comment]
The bug has been fixed. Thank you for reporting!
